### ISSUE TITLE
Server error when opening the Initial Setup Wizard

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#1003] opened 2018-07-09 15:23 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open the Initial Setup Wizard a server error pops up: 

![2018-07-06 09_14_48-metasfresh](https://user-images.githubusercontent.com/18696715/42459805-bed1dcf6-839c-11e8-963a-b2f6a00d478d.png)

in inspect you see the old error described here: 
https://github.com/metasfresh/metasfresh-webui-api/issues/438
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
No error.

**Comment by metasnw** [comment] 2018-08-31 06:27
duplicate of https://github.com/metasfresh/metasfresh-webui-api/issues/438

**Closed by metasnw** 2018-08-31 06:27 UTC
Labels: status:duplicate, type:bug
