### ISSUE TITLE
Tab crashes when changing window permissions on automatic role

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#365] opened 2017-05-11 12:54 UTC
### Is this a bug or feature request?
bug

### What is the current behavior?
tab crashes when changing one of many window permissions 

#### Which are the steps to reproduce?

- open Rolle Verwaltung
- select Admin
- select Window Access
- changing record "Bank" to inactive
- clicking on next record
- NOK: Chrome Tab Crashes

![image](https://cloud.githubusercontent.com/assets/16079655/25950277/a7e2ce96-365a-11e7-8a63-0dd8f626ce22.png)

**Comment by teosarca** [comment] 2017-05-14 20:46
waiting for https://github.com/metasfresh/metasfresh-webui-frontend/issues/745

**Comment by teosarca** [comment] 2017-05-16 06:17
Status update:
* added PKs to almost all AD*Access tables (AD_Window_Access, AD_Process_Access etc)
* browser tab still freezes:
** TODO: on backend side we shall reduce the document PATCH response body => shall be fixed by https://github.com/metasfresh/metasfresh-webui-api/issues/378
** TODO: on frontend side we shall "avoid" freezing when frontend got a huge reponse => shall be fixed (if possible) on https://github.com/metasfresh/metasfresh-webui-frontend/issues/745

**Comment by teosarca** [comment] 2017-05-21 16:14
Fixed in https://github.com/metasfresh/metasfresh-webui-api/issues/378

**Comment by teosarca** [comment] 2017-05-21 16:28
Note to IT:

## Test
You can test this with any document where you have a lot of records in one of it's included tabs.
e.g.
* a role (not manual) because it has a lot of data in window/process/etc access tabs
* prepared this product too, it has a lot of CU-TU assignments: https://w101.metasfresh.com:8443/window/140/2005632

Try editing the header. Try also activating/deactivating the header.
Try editing one of it's children.
Try clearing some mandatory to make the document invalid. The try setting it back.

In all tests, please also pay attention to:
* when tab becomes readonly
* when tab's New, Batch entry and Delete actions are available.
* when valid/saved status changes (i.e. red line is shown or not)

## Regression
* test main windows, like sales order.
* try completing a document => lines shall be readonly

**Comment by metas-lc** [comment] 2017-05-22 12:57
IT

(the NOK is about included tabs being editable even if the header is inactive)

tested subtabs from Role window, making lines active or inactive. Also made changes in header => worked fine
tested also the product with lots of assignments => works the same

when tab becomes readonly:
- on document complete - Yes OK
- on inactive header - No NOK

when tab's New, Batch entry and Delete actions are available
- new document, mandatory fields not set - Not available OK
- inactive document - Not available OK
- drafted/ in progress document - available OK
- completed document - Not available OK

Try clearing some mandatory to make the document invalid. The try setting it back
- works fine

**Comment by metas-lc** [comment] 2017-05-26 12:39
IT
1. retested testcase above - works fine OK
2. complete and reactivate a document (e.g. an order) => you can edit it OK

**Closed by metas-lc** 2017-05-26 12:39 UTC
Labels: status:IT-failed, type:bug
