### ISSUE TITLE
Language Field Zoom-To leads to an error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#421] opened 2017-05-28 11:20 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Language Field Zoom-To leads to an error.
#### Which are the steps to reproduce?
Open the Business Partner Window /window/123. Press Zoom-To Link on Field Language. Error.
### What is the expected or desired behavior?
Zoom to Language Window w/o an error message.

![image](https://cloud.githubusercontent.com/assets/13365687/26528275/42d691d0-43a8-11e7-8285-220ffde2be7e.png)

**Comment by teosarca** [comment] 2017-05-29 05:01
duplicate of #417

**Closed by teosarca** 2017-05-29 05:01 UTC
Labels: type:bug
