### ISSUE TITLE
Empties window without pre-selection possible

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#332] opened 2017-04-27 11:38 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, you cannot do the Quick actions "Empties ..." w/o selecting a material receipt candidate line.
#### Which are the steps to reproduce?
Open The Material Receipt candidates window and try.
### What is the expected or desired behavior?
Allow the Quick actions for empties also w/o preselecting a line.
![image](https://cloud.githubusercontent.com/assets/13365687/25481700/ae73ca06-2b4e-11e7-9df7-3567cfef12b5.png)

**Comment by teosarca** [comment] 2017-04-27 14:38
Note to IT: besides task scope, full IT on empties functionality is required

**Comment by metas-lc** [comment] 2017-04-28 13:51
IT
tested empties on webui 
=> empties receive
* works fine without selecting a line
* works fine selecting a line (bpartner is set)
=> empties return
* works fine without selecting a line
* works fine selecting a line (bpartner is set)

only thing i noticed is that on empties receive, if you create one manually, you have to set the document number. Created issue: https://github.com/metasfresh/metasfresh/issues/1400

**Comment by metas-dh** [comment] 2017-04-28 15:32
regression testing for empties in Swing:

Creating empties returns in Wareneingang POS:
* works fine when selecting a line (bpartner is set): only possible for Leergut Rückgabe, from vendor, like before
* works fine without selecting a line: both Leergut Rücknahme & Leergut Rückgabe, like before
* compared the jaspers with Gebindekontokorrent, Gebindesaldo & Gebindeübersicht: empties returns were included and overall Saldi were correct

**Comment by metas-lc** [comment] 2017-05-26 13:09
NOK: go to any empties window and create a new one and add a line with add new
=> notice that you have a red line even if you didn't remove any mandatory fields NOK
=> you can't add any product. Nothing is found NOK
(if you add a product from batch entry it works)
see https://w101.metasfresh.com:8443/window/540322/1003737

**Comment by metas-lc** [comment] 2017-06-14 14:13
re-checking the issue: 
empties windows : 540323 and 540322, 53098 and 53097
=> you can add products with add new OK
=> there is still a red line when you open add new in 540322 and 53098, but i think this is frontend issue

**Comment by teosarca** [comment] 2017-06-15 08:08
Fixed by making the M_Product_ID field (the field and NOT the column) mandatory for those 2 windows (540322 and 53098).
On table level, the M_InOutLine.M_Product_ID is not mandatory because we still have support for description lines (which does not have a product set).
Setting it as mandatory on window/field level would tell the webui that the product is mandatory in that window and the webui shall not try to save it if the product field is not filled.

**Comment by metas-rc** [comment] 2017-06-16 14:21
Results of IT

* Empties return and Empties receive are both available for material receipt candidates even if no line is created
* Empties receive has some UI problems but there will be a followup for fixing it on webui : 
https://github.com/metasfresh/metasfresh/issues/1836
* Regression: Emptiese receive and Empties return both work correctly with a pre-selected line

**Closed by metas-rc** 2017-06-16 14:21 UTC
Labels: branch:master, branch:release, priority:high, type:enhancement
