### ISSUE TITLE
Remaining TU Qty in Quickaction and HU Config

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#228] opened 2017-03-07 15:18 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, always the config of a full palette/ LU is shown in the QuickAction Button of Material Receipt Schedule Window.
#### Which are the steps to reproduce?
Open the Window and check.
### What is the expected or desired behavior?
When receiving the Products then show the remaining Qty in the Quick action Button:
a) If the remaining qty is > 0 and less than a full palette --> show the remaining Qty
b) If the remaining qty is > 0 and more or equal than a full palette --> show the max qty of palette (like now)
c) If the remaining qty is = 0 --> show the max qty of palette (like now)

![image](https://cloud.githubusercontent.com/assets/13365687/23662962/7840b266-0351-11e7-910e-1932fc27ae08.png)

**Comment by metas-dh** [comment] 2017-03-09 07:58
Results from IT 1
tested on w101:

* when i leave the attribute set originally suggested for my product, then the qty TU in action button is shown correctly, e.g. 48 G2 x 10kg, for my order of 50 TUs; it's also correclty reduced after partial receipt
![2017-03-08 15_47_49-metasfresh](https://cloud.githubusercontent.com/assets/18696715/23740990/7a420492-04a6-11e7-9e2a-5742504a411e.png)

* when i change the attribute set, however, then the qty TU in action button always shows 1 G2 x 10kg, although i also ordered 50 TUs of that, and it remains 1 G2 x 10kg, after partial receipts as well
![2017-03-08 15_48_07-metasfresh](https://cloud.githubusercontent.com/assets/18696715/23741007/8c968e2e-04a6-11e7-81b6-8ffcdbb9ccbe.png)

**Comment by teosarca** [comment] 2017-04-24 00:02
is it still reproductible?

**Comment by metas-dh** [comment] 2017-04-26 07:56
checked again, could not reproduce: moving to Done.

**Closed by metas-dh** 2017-04-26 07:56 UTC
Labels: enhancement, integrated, IT failed, release-candidate
