### ISSUE TITLE
Document Line Delete Behaviour

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#272] opened 2017-03-29 11:54 UTC
### Is this a bug or feature request?
* Feature request
### What is the current behavior?
* When a document line ( e.g. Purcahse Order line)  is deleted it still appears in the list even if it doesn't exist any more.
#### Which are the steps to reproduce?
* Create a purchase order, add a line for it, delete the line.
* => NOK: The line was deleted but it still appears in the list
### What is the expected or desired behavior?
* The backend should somehow comunicate to the frontend that that line does not exist any more ( a "Deleted" flag) . The frontend shall update the UI accordingly.

Fronend counterpart: https://github.com/metasfresh/metasfresh-webui-frontend/issues/588

**Comment by metas-dh** [comment] 2017-04-10 10:05
Frontend issue was closed since the problem couldn't be reproduced, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/588#issuecomment-290384888

Closing this issue as well, since problem seems fixed for now.

**Closed by metas-dh** 2017-04-10 10:05 UTC
Labels: enhancement, integrated, release-candidate
