### ISSUE TITLE
Show full caption on mouse over 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#519] opened 2017-07-24 08:08 UTC
### Is this a bug or feature request?
feature request

### What is the current behavior?
If fields or tab names are cut off you can not see em anymore:
https://forum.metasfresh.org/t/webui-grundsaetzlich-bei-allen-textausgaben/515

#### Which are the steps to reproduce?
go to
https://w101.metasfresh.com:8443/window/111/540024

and try to read the tab caption of "Permission Re..." with full hd

### What is the expected or desired behavior?
have a mouse over that shows the full name "Permission Requests"

**Comment by teosarca** [comment] 2017-07-24 08:09
duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1051

**Closed by teosarca** 2017-07-24 08:09 UTC
Labels: type:enhancement
