### ISSUE TITLE
Handling Unit Editor Action Internal Usage not possible for more than 1 Page

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api#668] opened 2017-11-09 14:11 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user cannot "select All" and use Internal Usage Action. Only select all on Page works.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Shall also work for "Select All" in HU Editor https://w101.metasfresh.com:8443/window/540189

**Comment by teosarca** [comment] 2017-11-13 11:22
note to IT: besides testing the task, FULL REGRESSION is needed.
Check some standard views (order etc), check picking terminal, manufacturing issue/receipt, HU editor etc.

**Comment by metas-dh** [comment] 2017-11-16 08:13
Results of IT1
tested in sp80 (more HUs in Editor to test with)

1. Open Handling Unit Editor, filter for active HUs in a certain warehouse: 11 pages
2. Select all with [ctrl]+a: all HUs in the current page are selected, OK
3. Check next page: nothing selected: NOK i think, afaiu all HUs shall be selected in all pages?
4. Select all HUs in the current page with [ctrl]+a, select Internal Usage (Materialentnahme) in Action menu: all selected HUs from the page disappear, OK
(5. Check notification: no notification about the movement created for the Materialentnahme; didn't we usually get a notification about that? Movements were created correctly, though))
6. Check next page: all HUs still there, NOK
7. Go back to page 1: Empty, "Es sind noch keine Detailzeilen vorhanden", but 10 more pages exist; you have to run the filter again to get HUs displayed on the 1st page

**Comment by metas-dh** [comment] 2017-11-16 12:42
update:
checked with metas-mk: to select all HUs in all pages, use 2x [ctrl]+a
=> 2x [ctrl]+a, and Internal Usage (Materialentnahme): all HUs are moved, and not displayed anymore in Handling Unit Editor: OK

no HUs selected when turning the page: Keeping lines selected when turning the page not working #682

**Comment by metas-dh** [comment] 2017-11-16 15:20
Regression testing:

* manufacturing: issue / receipt working fine (partial issue, reverse, pick etc.)
* picking: picking working fine (pick, reverse, source HU etc.)

question: 
using [ctrl]+a in a HU Editor with 2 sides, e.g. manufacturing: when i use [ctrl]+a in HU Editor on the right side bc i want to select all available HUs for issueing, than all lines in both sides are selected, and the Action menu is not available anymore, so i can't issue; is that OK?

![2017-11-16 16_15_29-](https://user-images.githubusercontent.com/18696715/32898886-b1dff616-cae9-11e7-9e14-9a9efe684879.png)


same in picking: i can only use select all from this side, not [ctrl]+a to select all available HUs for picking

**Comment by teosarca** [comment] 2017-11-21 12:30
@metas-dh  now i cannot reproduce... might be because shortcuts where recently changed.
Also, as it sounds like it seems to be a frontend issue if i understand it correctly.

@metas-mk  wdyt?

**Comment by metas-dh** [comment] 2018-01-19 11:08
created https://github.com/metasfresh/metasfresh-webui-frontend/issues/1515, closing this one

**Closed by metas-dh** 2018-01-19 11:08 UTC
Labels: branch:master, branch:release, priority:high, type:enhancement
