### ISSUE TITLE
Error when opening Business Partner Single View in particular case

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#361] opened 2017-05-11 11:34 UTC
### Is this a bug or feature request?
bug

### What is the current behavior?
when double clicking on the first partner I get this:
![image](https://cloud.githubusercontent.com/assets/16079655/25947149/89488da6-364e-11e7-9198-4dcc308dcb28.png)

#### Which are the steps to reproduce?
A Cache Reset solved it as workaround and since then I can't

### What is the expected or desired behavior?
Avoid this case

**Comment by teosarca** [comment] 2017-05-11 12:28
cannot reproduce. agreed with @metasnw  to close it.

**Closed by teosarca** 2017-05-11 12:28 UTC
Labels: bug, invalid
