### ISSUE TITLE
Hide Roles on Logon that are not ideal for WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-api#376] opened 2017-05-15 13:19 UTC
### Is this a bug or feature request?
feature

### What is the current behavior?
users get constantly confused about the roles: sysadmin, quickstart, admin, webui

#### Which are the steps to reproduce?
logon

### What is the expected or desired behavior?
have a checkbox on ad_role with options: hide in webui
implement only in webui and leave java client as he is

**Comment by teosarca** [comment] 2017-06-01 04:50
Update: introduced "Is webui role" flag to Role window. By default is checked.
If unchecked, the role will not be visible on webui login.


![image](https://cloud.githubusercontent.com/assets/1244701/26664993/fde4d43e-469e-11e7-8f1a-988001921e98.png)

**Comment by teosarca** [comment] 2017-06-01 04:51
Note to IT:
* regression: quick test swing client and try to login; the role shall be available no matter if it's flagged as webui or not (because we are in Swing)

**Comment by metas-mk** [comment] 2017-06-07 05:28
Tested on Swing and WebClient. Works as required. Done/ Closing.

**Closed by metas-mk** 2017-06-07 05:28 UTC
Labels: branch:master, branch:release, type:enhancement
