### ISSUE TITLE
KPIs in RC showing error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api#905] opened 2018-03-15 11:19 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
The KPIs in the current RC show only "Error loading data..."
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
KPIs shall be displayed.

**Comment by metas-ts** [comment] 2018-03-15 13:44
duplicate of https://github.com/metasfresh/metasfresh/issues/3671

**Closed by metas-ts** 2018-03-15 13:44 UTC
Labels: priority:high, type:bug
