### ISSUE TITLE
Picking Tray Clearing: packing HUs: Add to Transportation Order, Ship and Invoice action

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api#763] opened 2017-12-19 08:16 UTC
### Is this a bug or feature request?
part of https://github.com/metasfresh/metasfresh/issues/3190

similar with https://github.com/metasfresh/metasfresh-webui-api/issues/751

### What is the expected or desired behavior?
* open Picking Tray Clearing
* select a picking slot
* make sure you have some HUs in the right side view
* select one or more and call the new "Add to Transportation Order, Ship and Invoice" action
the action opens and user is able to select an open Transportation Order
When the process is executed, it shall
* create M_Package(s), M_Package_HU(s) and link them to given Transportation Order
* the HUs added to the transportation order shall no longer be visible in the right side view, nor later.
* creates a shipment for those HUs (shipment schedules are updated correctly)
* creates an invoice for
**  all invoice candidates which are "linked" to those shipment schedules of those HUs
** invoice candidates which have a Invoice Schedule set are skipped. They will be invoiced on that schedule (e.g. monthly, weekly etc)

User shall get a notification when:
* the shipment is generated
* the invoice is generated (if any)
* something went wrong (e.g. invoice generate workpackage(s) failed)

### Note to IT
* regression make sure generating shipments from HUs still works in Swing
* regression on generating Invoices
* re-test https://github.com/metasfresh/metasfresh/issues/1905, see below

**Comment by teosarca** [comment] 2017-12-19 08:23
update: partial developed

**Comment by teosarca** [comment] 2017-12-21 14:38
Hotfixed error when generating the receipt in Swing.
As as side effect, https://github.com/metasfresh/metasfresh/issues/1905 shall be retested because on Swing the code introduced there was not executed, because the receipts were not collected.

The error stacktrace was:
```
Caused by: org.adempiere.exceptions.AdempiereException: Cannot provide the generated shipments because the result was not configured to retain them
    at de.metas.inoutcandidate.api.impl.DefaultInOutGenerateResult.getInOuts(DefaultInOutGenerateResult.java:87)
    at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules0(HUReceiptScheduleBL.java:384)
    at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.lambda$0(HUReceiptScheduleBL.java:290)
    at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:771)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:683)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:584)
    at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:515)
    at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules(HUReceiptScheduleBL.java:290)
    at de.metas.handlingunits.client.terminal.select.api.impl.ReceiptScheduleFiltering.processRows(ReceiptScheduleFiltering.java:245)
    at de.metas.handlingunits.client.terminal.select.model.AbstractHUSelectModel.processRows(AbstractHUSelectModel.java:627)
```

**Comment by metas-dh** [comment] 2018-01-08 13:27
Results of IT1
tested in mf15

When the process is executed, it shall:
* create M_Package(s), M_Package_HU(s) and link them to given Transportation Order:
  * M_Package (Packstück) is created: OK
  * M_Package linked to Transportation Order: OK (link wo window in tab Versandpackung)
  * M_Package_HU(s): not sure where to find this one?
* the HUs added to the transportation order shall no longer be visible in the right side view, nor later: OK
* creates a shipment for those HUs (shipment schedules are updated correctly): OK
* creates an invoice for
  * all invoice candidates which are "linked" to those shipment schedules of those HUs: OK
  * invoice candidates which have a Invoice Schedule set are skipped. They will be invoiced on that schedule (e.g. monthly, weekly etc): to be tested
* User shall get a notification when:
  * the shipment is generated: OK
  * the invoice is generated (if any): OK
   * something went wrong (e.g. invoice generate workpackage(s) failed): to be tested

questions:
* when the invoice is created, the shipment schedule is closed, so if you use this process to create a partial shipment, no other shipments can be created for the resp. schedule: i guess this is wanted?

* Transportation Order in WebUI: shows the M_ShipperTransportation_ID in tab Versandpackung, not the no. of the transportation order, but in Swing it's the no., why?

WebUI:
![2018-01-08 14_11_52-metasfresh](https://user-images.githubusercontent.com/18696715/34672309-3f45f416-f47e-11e7-8ca3-b7284b1149b3.png)

Swing:
![2018-01-08 14_12_35-decloudit001](https://user-images.githubusercontent.com/18696715/34672319-45f1d190-f47e-11e7-8cbc-653ba70f546f.png)

still need to do:
* regression make sure generating shipments from HUs still works in Swing
* regression on generating Invoices
* re-test metasfresh/metasfresh#1905

**Comment by metas-dh** [comment] 2018-01-10 12:34
Regression testing:

* generating shipments from HUs still works in Swing:
  * generating shipments from shipment schedule for picked HUs: OK
  * generating shipments from Verdichtung POS for picked HUs: OK
  * generating shipments from shipment schedules without picked HUs: OK

* regression on generating Invoices:
  * tested in Swing for the orders i created the different shipments for (see above): OK
  * tested in WebUI  for the orders i created the different shipments for (see above):  could not create an invoice for 1 order, but could not reproduce
* re-test metasfresh/metasfresh#1905: 
  * tested in Swing: OK,
  * could not test in WebUI bc of Transform not working correctly (trying to reproduce and creating a task)

**Comment by metas-dh** [comment] 2018-01-11 14:24
Update:
* invoice candidates which have a Invoice Schedule set are skipped. They will be invoiced on that schedule (e.g. monthly, weekly etc): 
=> Invoice Schedule for my IC was 14 days, but invoice was created anyway; IC still says "Date Invoice from eff.: 15.01.2018", invoice date is 11.01.2018
@teosarca i think this is NOK?

**Comment by metas-dh** [comment] 2018-01-25 12:19
created follow up: #806, closing this one.

**Closed by metas-dh** 2018-01-25 12:19 UTC
Labels: branch:master, branch:release, priority:high, type:enhancement
