### ISSUE TITLE
Bug in Warehouse window: Auftragsübersicht (intern) NPE

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-api#263] opened 2017-03-20 15:42 UTC
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Clicking on Auftragsübersicht (intern)  in referenced dcuments list leads to a null pointer exception.
#### Which are the steps to reproduce?
* Go to a warehouse which has referenced documents, click on Auftragsübersicht (intern)
* => NOK: There is an error message displayed in top right

![image](https://cloud.githubusercontent.com/assets/16001442/24107772/5639352e-0d94-11e7-81c3-9af12ab0d919.png)

* => NOK: There is a "NoMenuNodesFoundException" if I check inspection: 
![image](https://cloud.githubusercontent.com/assets/16001442/24107844/89cbf5f2-0d94-11e7-8906-c4609e651bb0.png)

* => There is a NPE if I check inspection: 

![image](https://cloud.githubusercontent.com/assets/16001442/24107866/9bbe5458-0d94-11e7-9fc0-dff289ce138b.png)

**Comment by teosarca** [comment] 2017-03-22 16:37
Note to IT:
* regression: check Auftragsübersicht (intern) window (RV_C_OrderLine_Overview) in swing UI. shall be ok

**Comment by metas-lc** [comment] 2017-03-27 11:56
IT
- no NPE OK
- data is visible OK
- still get the error "No menu node found for type=Window and elementId=540089" NOK
- checked swing: navigating through tabs (up->down and back) there is this warning "No key Found on GridTable[RV_M_InOutLine_Overview,WindowNo=4,Tab=2]. Returning NULL."

**Comment by teosarca** [comment] 2017-03-27 11:58
IMHO it's OK because
* "still get the error "No menu node found for type=Window and elementId=540089" NOK" => yup, we don't have that intern window in the menu
* we don't support this window atm
* i've just fixed the things around the framework....

**Comment by metas-lc** [comment] 2017-03-27 11:59
Thank you. Then i'm moving it to done

**Closed by metas-lc** 2017-03-27 11:59 UTC
Labels: bug, integrated, release-candidate
